import streamlit as st

def initialize_session_state():
    """
    Initialize all relevant keys in st.session_state, plus the wizard_step.
    """
    if "wizard_step" not in st.session_state:
        st.session_state["wizard_step"] = 1

    keys = [
        "job_title",
        "company_name",
        "brand_name",
        "headquarters_location",
        "company_website",
        "date_of_employment_start",
        "job_type",
        "contract_type",
        "job_level",
        "city",
        "team_structure",
        "role_description",
        "reports_to",
        "supervises",
        "role_type",
        "role_priority_projects",
        "travel_requirements",
        "work_schedule",
        "role_keywords",
        "decision_making_authority",
        "role_performance_metrics",
        "task_list",
        "key_responsibilities",
        "technical_tasks",
        "managerial_tasks",
        "administrative_tasks",
        "customer_facing_tasks",
        "internal_reporting_tasks",
        "performance_tasks",
        "innovation_tasks",
        "task_prioritization",
        "hard_skills",
        "soft_skills",
        "must_have_skills",
        "nice_to_have_skills",
        "certifications_required",
        "language_requirements",
        "tool_proficiency",
        "domain_expertise",
        "leadership_competencies",
        "technical_stack",
        "industry_experience",
        "analytical_skills",
        "communication_skills",
        "project_management_skills",
        "soft_requirement_details",
        "visa_sponsorship",
        "salary_range",
        "currency",
        "pay_frequency",
        "commission_structure",
        "bonus_scheme",
        "vacation_days",
        "flexible_hours",
        "remote_work_policy",
        "relocation_assistance",
        "childcare_support",
        "recruitment_steps",
        "recruitment_timeline",
        "number_of_interviews",
        "interview_format",
        "assessment_tests",
        "onboarding_process_overview",
        "recruitment_contact_email",
        "recruitment_contact_phone",
        "application_instructions",
        "parsed_data_raw",
        "language_of_ad",
        "translation_required",
        "employer_branding_elements",
        "desired_publication_channels",
        "internal_job_id",
        "ad_seniority_tone",
        "ad_length_preference",
        "deadline_urgency",
        "company_awards",
        "diversity_inclusion_statement",
        "legal_disclaimers",
        "social_media_links",
        "video_introduction_option",
        "comments_internal",
    ]

    for k in keys:
        if k not in st.session_state:
            st.session_state[k] = ""
